<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
    <h1>Bem vindo ao EasyWiki</h1>
    <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
    <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<!-- Example row of columns -->
<div class="row">
    <? foreach ($this->posts as $post): ?>
        <div class="span4">
            <h2><? echo $post->title; ?></h2>
            <p><? echo substr($post->content, 0, 50) . "..."; ?></p>
            <p><a class="btn" href="#">Ler mais &raquo;</a></p>
        </div>

    <? endforeach; ?>
</div>