<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>EasyWiki</title>
        <!-- Bootstrap -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
    </head>
    <body>
        
        <? echo $this->render('main_menu.phtml'); ?>
       
        <div class="container">
            <?php
            $session = Zend_Registry::get('session');
            if(isset($session->erro)) {
                echo "<div class='alert alert-error'>
                        $session->erro
                        <button type='button' class='close' data-dismiss='alert'>×</button>
                      </div>";
                unset($session->erro);
            }
            ?>
            
            <?php echo $this->layout()->content; ?>
            <footer>
                <hr>    
                <p>&copy; Company 2012</p>
            </footer>
        </div>
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script>$(".alert").alert('teste')</script>
        
    </body>
</html>

