<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>EasyWiki</title>
        <!-- Bootstrap -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <style type="text/css">
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
    </head>
    <body>
        <? echo $this->render('main_menu.phtml'); ?>
        
        <div class="container">

            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <h1>Bem vindo ao EasyWiki</h1>
                <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
                <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
            </div>
            
            <?php echo $this->layout()->content; ?>
            <hr>

            <footer>
                <p>&copy; Company 2012</p>
            </footer>

            <script src="http://code.jquery.com/jquery-latest.js"></script>
            <script src="/js/bootstrap.min.js"></script>
    </body>
</html>

