<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">EasyWiki</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li><a href="/post/list">Artigos</a></li>
                    <li><a href="/contact">Contato</a></li>
                    <li>
                <?
                    $auth = Zend_Auth::getInstance();
                    if ($auth->hasIdentity()) {
                        echo "<a href=/auth/logout>Logout</a>";
                    } else {
                        echo "<a href=/auth/login>Login</a>";
                    } 
                ?>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>