<h1>Posts</h1>

<table class="table table-hover">   
<? foreach($this->posts as $post): ?>
    <tr>
        <td><? echo $post->title; ?></td>
        <td><? echo $post->content; ?></td>
        <td><? echo $post->created; ?></td>
        <td><a class="btn btn-small" href="#"><i class="icon-pencil"></i></a></td>
        <td><a class="btn btn-small" href="#"><i class="icon-trash"></i></a></td>
    </tr>
<? endforeach; ?>
</table>