<h1>Posts</h1>

<div class="span1 offset11">
    <a class="btn btn-small btn-primary" href="/post/create">Novo</a>
</div>
&nbsp;

<table class="table table-hover">   
    <? foreach ($this->posts as $post): ?>
        <tr>
            <td><? echo substr($post->title, 0, 30); ?></td>
            <td><? echo substr($post->content, 0, 50) . "..."; ?></td>
            <td><? echo $post->created; ?></td>
            <td><a class="btn btn-small" href="/post/read/id/<? echo $post->id; ?>"><i class="icon-search"></i></a></td>
            <td><a class="btn btn-small" href="/post/update/id/<? echo $post->id; ?>"><i class="icon-pencil"></i></a></td>
            <td><a class="btn btn-small" href="/post/delete/id/<? echo $post->id; ?>"><i class="icon-trash"></i></a></td>
        </tr>
    <? endforeach; ?>
</table>