<h1>Posts</h1>

<div class="span1 offset11">
    <a class="btn btn-small btn-primary" href="#">Novo</a>
</div>
&nbsp;

<table class="table table-hover">   
    <? foreach ($this->posts as $post): ?>
        <tr>
            <td><? echo $post->title; ?></td>
            <td><? echo substr($post->content, 0, 50) . "..."; ?></td>
            <td><? echo $post->created; ?></td>
            <td><a class="btn btn-small" href="#"><i class="icon-pencil"></i></a></td>
            <td><a class="btn btn-small" href="#"><i class="icon-trash"></i></a></td>
        </tr>
    <? endforeach; ?>
</table>